# Generated by Django 2.2 on 2019-05-18 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2019)])),
                ('title', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('link', models.URLField(null=True)),
                ('details', models.TextField(help_text='Use a Markdown syntax', null=True)),
                ('expire', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2019)])),
                ('title', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('link', models.URLField(null=True)),
                ('details', models.TextField(help_text='Use a Markdown syntax', null=True)),
            ],
            options={
                'verbose_name_plural': 'diploma',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.DateField(verbose_name='date started')),
                ('duration', models.DurationField()),
                ('job_type', models.CharField(max_length=100)),
                ('compagny', models.CharField(max_length=100)),
                ('compagny_url', models.URLField(null=True)),
                ('decription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date published')),
                ('typeof', models.CharField(max_length=20)),
                ('journal', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='my_site_title', max_length=100)),
                ('about', models.TextField()),
                ('owner_first_name', models.CharField(default='my_first_name', max_length=100)),
                ('owner_last_name', models.CharField(default='my_last_name', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nesting_level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('slug', models.SlugField(allow_unicode=True, max_length=60)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_category', to='website.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_written', models.DateField(auto_now_add=True)),
                ('last_udate', models.DateField(verbose_name='date published')),
                ('tags', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default='Misc', on_delete=django.db.models.deletion.SET_DEFAULT, to='website.Category')),
            ],
            options={
                'ordering': ('last_udate',),
            },
        ),
    ]
