# Generated by Django 2.2 on 2019-05-18 11:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.AlterField(
            model_name='category',
            name='nesting_level',
            field=models.IntegerField(default=0, help_text='Leave it how it is. The app takes care of everything', validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='certification',
            name='details',
            field=models.TextField(blank=True, help_text='Use a Markdown syntax', null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='details',
            field=models.TextField(blank=True, help_text='Use a Markdown syntax', null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
